# Generated by Django 3.0.8 on 2020-10-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201022_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='sd',
            field=models.BooleanField(default=True, verbose_name='Наличие SD карты'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='sd_volum_max',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Максимальный объем встраеваемой памяти'),
        ),
    ]
