# Generated by Django 3.0.8 on 2020-10-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20201022_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartphone',
            old_name='sd_volum_max',
            new_name='sd_volume_max',
        ),
    ]
