# Generated by Django 3.1.2 on 2020-10-26 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20201022_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='in_other',
            new_name='in_order',
        ),
    ]
